name: Validate Pull Request
run-name: >-
    "${{ github.actor }}"가 제출한 과제를 검토하고 있습니다. 🚀
on:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - ready_for_review
            - unlocked
            - synchronize
jobs:
    Validate-Pull-Request:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: 1개의 파일만 수정되었는지 검사
              uses: JJ/github-pr-contains-action@releases/v11
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
                  filesChanged: 1
            - name: 제목 형식이 올바른지 검사
              uses: deepakputhraya/action-pr-title@master
              with:
                  regex: '^\[\d{2}주차 [가-힣]+\] .+'
                  github_token: "${{ secrets.GITHUB_TOKEN }}"
            - name: 파일의 경로가 올바른지 검사
              uses: brettcannon/check-for-changed-files@v1
              with:
                  # TODO: Replace hard-coded patterns
                  file-pattern: |
                    /[0-9][0-9]주차/@(김동주|이윤호|이은지|박민수|손성빈|박상우|정지원|조예빈)/*.@(c|cpp|py|java)
                    /[0-9][0-9]\\354\\243\\274\\354\\260\\250/@(\\352\\271\\200\\353\\217\\231\\354\\243\\274|\\354\\235\\264\\354\\234\\244\\355\\230\\270|\\354\\235\\264\\354\\235\\200\\354\\247\\200|\\353\\260\\225\\353\\257\\274\\354\\210\\230|\\354\\206\\220\\354\\204\\261\\353\\271\\210|\\353\\260\\225\\354\\203\\201\\354\\232\\260|\\354\\240\\225\\354\\247\\200\\354\\233\\220|\\354\\241\\260\\354\\230\\210\\353\\271\\210)/*.@(c|cpp|py|java)
                  token: "${{ secrets.GITHUB_TOKEN }}"
                  failure-message: >-
                    제출한 파일의 경로가 올바르지 않습니다.
                    파일의 이 올바른 디렉터리에 있는지 확인해주세요.
